Created Software Documentation.md
AlexTelon/FlexiCharge-BMS pull request #66
Opened 2023-09-21 10:45 UTC by KevFord

Added a file which is meant to hold some brief information about each piece of software added to the project.

2023-09-21 12:15 UTC, ljungqvistaxel requested changes

2023-09-21 12:15 UTC, ljungqvistaxel commented on Software Documentation.md
> +**About this document**
Markdown has titles in different sizes using "# " before the text. Try '#' for the title and '##' for the subtitles, without the lines underneath

2023-09-22 10:37 UTC, KevFord commented on Software Documentation.md
> +**About this document**
Updated the document to use proper markdown headings and removed the lines underneath the previous headings.

2023-09-25 13:13 UTC, ljungqvistaxel approved these changes

2023-09-25 13:15 UTC, merged